### ISSUE TITLE
Using COPY to Load Data and Permissions

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/amazon-redshift-developer-guide#12]
From reading the documentation:

I see the following: The role must have, at a minimum, the permissions listed in IAM Permissions for COPY, UNLOAD, and CREATE LIBRARY.

It would be nice to either have notes/pointers on either of these pages mentioning that if data is encrypted, permissions must also be on the KMS Key Policy and the IAM user or role needs to have KMS permissions as well.

https://docs.aws.amazon.com/redshift/latest/dg/loading-data-access-permissions.html
https://docs.aws.amazon.com/redshift/latest/dg/c_loading-encrypted-files.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
