### ISSUE TITLE
SHOW PROCEDURE not displaying procedure definition

### ISSUE THREAD

**Issue by ijoel92** [awsdocs/amazon-redshift-developer-guide#14]
I can create (and replace) a store procedure correctly but the definition can't be retrieved by using SHOW PROCEDURE sp_name or SHOW PROCEDURE sp_name(arg_name arg_type,...)

Only the following is displayed:
0 rows affected
SHOW executed successfully

I am able to find it exists with the following query but how to see the definition?

SELECT *
FROM PG_PROC_INFO
WHERE proowner<>1

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
