### ISSUE TITLE
Clicking the LoadingDataSampleFiles.zip link leads to AccessDenied error.

### ISSUE THREAD

**Issue by iamkilroy** [awsdocs/amazon-redshift-developer-guide#16]
Unable to download the LoadingDataSampleFiles.zip file that is referred to on: https://docs.aws.amazon.com/redshift/latest/dg/tutorial-loading-data-download-files.html

When clicking the link, the error returned is:
![image](https://user-images.githubusercontent.com/46033874/66890401-e9525580-ef9a-11e9-81ad-2284fb42d3c5.png)

Error is consistent across multiple browsers and ISPs.

**Comment by mjalkio** [comment]
Seems to be working for me, are you still having issues?

**Comment by iamkilroy** [comment]
Nope - issue is now resolved. Thx!
