### ISSUE TITLE
`ALTER FUNCTION` is missing

### ISSUE THREAD

**Issue by minamijoyo** [awsdocs/amazon-redshift-developer-guide#2]
The following SQL seems to be working, but it is undocumented.

```sql
ALTER FUNCTION function_name OWNER TO new_owner
```

**Comment by jeffs-fff** [comment]
Hello from 2021! Still missing :)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
