### ISSUE TITLE
queues and concurrency level

### ISSUE THREAD

**Issue by aijunpeng** [awsdocs/amazon-redshift-developer-guide#29]
Hey, is the following statement true? I was told that the total concurrency for WLM regardless of number of queues is 50. Based on this statement, a WLM can support 400(=8*5) queries? 

"You can define up to eight queues. Each queue can be configured with a maximum concurrency level of 50"

**Comment by aijunpeng** [comment]
Sorry I meant 400 = 8*50

**Comment by keithhc2** [comment]
@aijunpeng Sorry for the late response here. Yes, that is my understanding as well. 400=8*50. Closing this issue now. Feel free to submit a feedback ticket using the Provide feedback link at the bottom of this page if you experience any issues: https://docs.aws.amazon.com/redshift/latest/dg/c_workload_mngmt_classification.html
