### ISSUE TITLE
description for stl_query.starttime is wrong

### ISSUE THREAD

**Issue by ZacharyRSmith** [awsdocs/amazon-redshift-developer-guide#39]
It is "Time in UTC that the query started executing" but as seen by the below query, the time is actually before the query is put into a service class, let alone actually started executing:
```sql
select stl_query.starttime, stl_wlm_query.*
from stl_query
join stl_wlm_query
    using(query)
limit 1
```
Please change to "Time in UTC that the query started processing", "Time in UTC that the query was accepted", or be vague like other Redshift doc pages: "Time in UTC that the query started".

Similarly for endtime.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
