### ISSUE TITLE
description for table column position in stl_load_errors page is wrong

### ISSUE THREAD

**Issue by ZacharyRSmith** [awsdocs/amazon-redshift-developer-guide#40]
On this page: https://docs.aws.amazon.com/redshift/latest/dg/r_STL_LOAD_ERRORS.html

The description for table column position is "Position of the error in the field." when it should be "Position of the error in the raw_line" because on this page "the field" means "the table column", not "the raw_line".

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
