### ISSUE TITLE
service_class_name missing from doc'd columns in stl_wlm_query

### ISSUE THREAD

**Issue by ZacharyRSmith** [awsdocs/amazon-redshift-developer-guide#41]

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
