### ISSUE TITLE
Unsupported Type

### ISSUE THREAD

**Issue by yousefcodes** [awsdocs/amazon-redshift-developer-guide#47]
I'm getting an error while creating a table with the SUPER data type.

`[Amazon](500310) Invalid operation: Column "table_name.column_name" has unsupported type "super".`

I'm running the same script I used to run to create my database, but as of cluster version `1.0.23412` it no longer shows as supported when I try to use this data type.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
