### ISSUE TITLE
The last column, "avg_request_parallelism" appears twice https://docs.aws.amazon.com/redshift/latest/dg/r_SVL_S3QUERY.html

### ISSUE THREAD

**Issue by joaohps** [awsdocs/amazon-redshift-developer-guide#6]
The last column, "avg_request_parallelism", appears twice on the current doc page for the SVL_S3QUERY system log view.  The link to the page is: https://docs.aws.amazon.com/redshift/latest/dg/r_SVL_S3QUERY.html

It looks like a simple editing typo.  It would be nice to correct it when when the team gets a chance.

**Comment by keithhc2** [comment]
@joaohps Thanks for letting us know about the typo! It looks to be fixed now, so I'm closing this ticket.
