### ISSUE TITLE
Small Spelling issue

### ISSUE THREAD

**Issue by NeilJonkers** [awsdocs/amazon-redshift-developer-guide#61]
The following sentence [here](https://github.com/awsdocs/amazon-redshift-developer-guide/blob/8d2f6f8c9d8f6e7759dcd77bb56e314c287c7355/doc_source/copy-parameters-data-source-emr.md):

```
The following example loads data from as Amazon EMR cluster
```

Did we meant to say:

```
The following example loads data from an Amazon EMR cluster
```

Thank you

**Comment by keithhc2** [comment]
Should be fixed now with [52a5d10](https://github.com/awsdocs/amazon-redshift-developer-guide/commit/52a5d10fc37aff28e20110a6d26bbf6dd9a456d0). Thanks!
