### ISSUE TITLE
Note about DECIMAL type limitation not clear for NUMERIC

### ISSUE THREAD

**Issue by gmcorral** [awsdocs/amazon-redshift-developer-guide#7]
Hi,
The Note included in [this](https://github.com/awsdocs/amazon-redshift-developer-guide/blob/master/doc_source/r_Numeric_types201.md#decimal-or-numeric-type
) section states a limitation for the DECIMAL data type, but it seems a bit unclear that the limitation also applies for the NUMERIC data type.
Even if the docs indicates that both types are equivalent, it can be understood that the limitation can be avoided using the NUMERIC data type.
Regards

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
