### ISSUE TITLE
Is_integer function documentation needs update

### ISSUE THREAD

**Issue by hkaushal** [awsdocs/amazon-redshift-developer-guide#72]
As per the **is_integer** function's [documentation](https://github.com/awsdocs/amazon-redshift-developer-guide/blob/master/doc_source/r_is_integer.md), the function can expect a Column or A super. We ran into issue while we passed it a **Varchar** type field. Here is the code we ran
```
CREATE TEMP TABLE t(s char(100));
INSERT INTO t VALUES ('5');
SELECT s, is_integer(s) FROM t;
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
