### ISSUE TITLE
INTERVAL word is missing

### ISSUE THREAD

**Issue by pakapi** [awsdocs/amazon-redshift-developer-guide#9]
Please add INTERVAL word to this list.

**Comment by jrotenstein** [comment]
@pakapi You didn't include a link to the relevant page.

BTW, you can submit a change request by clicking Edit on the page and making the change yourself.

**Comment by pakapi** [comment]
Link: https://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html
I made a change.
